services:
    pg_db:
       image: postgres
       ports:
           -   2345:5432
       environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
       volumes:
         - pg_data:/var/lib/postgresql/data
    
    pgadmin4_ui:
       image: dpage/pgadmin4  
       ports:
         - 80:80
       environment:
           PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
           PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
volumes:
   pg_data: